all:
  children:
    srlinux:
      hosts:
        srl1:
          ansible_host: 172.24.0.101
        srl2:
          ansible_host: 172.24.0.102
      vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: nokia.srlinux.srlinux
        ansible_user: admin
        ansible_password: NokiaSrl1!