import base64
import datetime
import os
import re

import requests
import yaml  # available inside the NetBox container (PyYAML)
from dcim.models import Device, DeviceRole, Site
from extras.scripts import BooleanVar, ObjectVar, Script
from jinja2 import Template

POLICY_FILE = "srl_devices.yaml"
SELECTOR_FILE = "selector.yaml"
ORB_REPO = "admin/orb-policies"
SELECTOR_KEY = "srlinux_discovery"

# The block added to / removed from selector.yaml when activate_policy is toggled.
SELECTOR_BLOCK = {
    "selector": {"agent_name": "orb-agent"},
    "policies": {
        "srl_devices": {
            "path": "srl_devices.yaml",
            "enabled": True,
        }
    },
}

POLICY_TEMPLATE = """\
#-- version {{ version }}
# Generated by NetBox script RunOrbDiscovery at {{ timestamp }}.
# DO NOT EDIT BY HAND — re-run the script from NetBox Customization → Scripts.
# Devices: {{ scope | length }} active Nokia device(s) in {{ site.slug }} with role {{ role.name }}.
device_discovery:
  srl_devices:
    config:
      defaults:
        site: {{ site.name }}
        role: {{ role.name }}
    scope:
{%- for t in scope %}
      - driver: nokia_srl
        hostname: {{ t.address }}
        username: ${SRL_USERNAME}
        password: ${SRL_PASSWORD}
        optional_args:
            insecure: True
{%- endfor %}
"""


def _gitea_base_url():
    """Derive Gitea base URL from the workshop-resources Data Source config."""
    try:
        from core.models import DataSource
        ds = DataSource.objects.get(name='workshop-resources')
        m = re.match(r'(https?://[^/]+)', ds.source_url)
        return m.group(1) if m else ''
    except Exception:
        return os.environ.get('GITEA_URL', '')


class RunOrbDiscovery(Script):
    class Meta:
        name = "Run Orb Discovery"
        description = (
            "Renders srl_devices.yaml from NetBox and pushes it to Gitea. "
            "Filters: active Nokia devices with a primary IPv4 in the selected site and role."
        )
        commit_default = False

    site = ObjectVar(
        model=Site,
        label="Site",
        description="Site to query devices from",
    )

    role = ObjectVar(
        model=DeviceRole,
        label="Device Role",
        description="Device role to filter by and set as default in the discovery policy",
    )

    activate_policy = BooleanVar(
        default=True,
        label="Activate policy",
        description=(
            "Checked: add the srlinux_discovery block to selector.yaml so the Orb agent "
            "picks up the policy immediately. "
            "Unchecked: remove that block (suspends discovery without deleting the policy file)."
        ),
    )

    dry_run = BooleanVar(
        default=False,
        label="Dry run",
        description="Render and log the YAML without pushing to Gitea",
    )

    # ── Gitea helpers ──────────────────────────────────────────────────────────

    def _gitea_get(self, url, auth):
        """Fetch a file from Gitea. Returns (content_str, sha) or (None, None) if 404."""
        r = requests.get(url, auth=auth, timeout=10)
        if r.status_code == 404:
            return None, None
        if r.status_code == 401:
            raise requests.exceptions.HTTPError(
                "Gitea authentication failed (HTTP 401). Check admin password."
            )
        r.raise_for_status()
        data = r.json()
        return base64.b64decode(data["content"]).decode(), data["sha"]

    def _gitea_put(self, url, auth, content, sha, message):
        """PUT a file to Gitea with one SHA-mismatch retry."""
        for attempt in range(2):
            body = {
                "branch": "main",
                "content": base64.b64encode(content.encode()).decode(),
                "message": message,
            }
            if sha:
                body["sha"] = sha
            r = requests.put(url, auth=auth, json=body, timeout=10)
            if r.status_code == 409 and attempt == 0:
                self.log_info("SHA mismatch on PUT — refreshing SHA and retrying...")
                _, sha = self._gitea_get(url, auth)
                continue
            if r.status_code == 401:
                raise requests.exceptions.HTTPError(
                    "Gitea authentication failed (HTTP 401). Check admin password."
                )
            r.raise_for_status()
            return

    # ── selector.yaml management ───────────────────────────────────────────────

    def _update_selector(self, selector_url, auth, activate, timestamp):
        """Add or remove the srlinux_discovery block in selector.yaml."""
        existing, sha = self._gitea_get(selector_url, auth)

        if existing is None and not activate:
            self.log_info("selector.yaml not found and activate is off — nothing to do.")
            return

        try:
            current = yaml.safe_load(existing or "") or {}
        except yaml.YAMLError as e:
            self.log_failure(f"Could not parse selector.yaml: {e}")
            return

        already_present = SELECTOR_KEY in current

        if activate:
            if already_present:
                self.log_info(f"selector.yaml: '{SELECTOR_KEY}' block already present — no change.")
                return
            current[SELECTOR_KEY] = SELECTOR_BLOCK
            verb, past = "Add", "added"
        else:
            if not already_present:
                self.log_info(f"selector.yaml: '{SELECTOR_KEY}' block not present — nothing to remove.")
                return
            del current[SELECTOR_KEY]
            verb, past = "Remove", "removed"

        new_content = yaml.dump(current, default_flow_style=False, sort_keys=False, allow_unicode=True)
        self._gitea_put(
            selector_url, auth, new_content, sha,
            f"{verb} {SELECTOR_KEY} in selector.yaml at {timestamp}",
        )
        self.log_success(f"selector.yaml: '{SELECTOR_KEY}' block {past}.")

    # ── main ───────────────────────────────────────────────────────────────────

    def run(self, data, _commit):
        del _commit  # NetBox required signature; this script makes no ORM writes
        site = data["site"]
        role = data["role"]
        activate = data["activate_policy"]
        timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z")

        gitea_base = _gitea_base_url()
        gitea_auth = ('admin', 'netboxlabs')
        policy_url = f"{gitea_base}/api/v1/repos/{ORB_REPO}/contents/{POLICY_FILE}"
        selector_url = f"{gitea_base}/api/v1/repos/{ORB_REPO}/contents/{SELECTOR_FILE}"

        devices = Device.objects.filter(
            site=site,
            role=role,
            device_type__manufacturer__slug="nokia",
            status="active",
            primary_ip4__isnull=False,
        ).order_by("name")

        if not devices.exists():
            self.log_failure(
                f"No active Nokia devices with a primary IPv4 found in site '{site.slug}' "
                f"with role '{role.slug}'. "
                "Complete Module 2 Steps 1–5 (create the site, manufacturer, device type, "
                "device role, and devices with primary IPs) before running this script."
            )
            return

        scope = [
            {"device_name": d.name, "address": str(d.primary_ip4.address.ip)}
            for d in devices
        ]

        # Read the current version from Gitea so we can increment it.
        # Dry runs skip this and always show version 1 (they don't touch Gitea).
        version = 1
        existing_sha = None

        if not data["dry_run"]:
            try:
                existing_content, existing_sha = self._gitea_get(policy_url, gitea_auth)
            except requests.exceptions.RequestException as e:
                self.log_failure(
                    f"Gitea GET failed: {e}\n"
                    f"Check that Gitea is running and reachable at {gitea_base}"
                )
                return

            if existing_content:
                m = re.match(r'^#-- version (\d+)', existing_content)
                version = int(m.group(1)) + 1 if m else 1

        rendered_yaml = Template(POLICY_TEMPLATE).render(
            version=version,
            timestamp=timestamp,
            site=site,
            role=role,
            scope=scope,
        )

        if data["dry_run"]:
            self.log_info(
                f"Dry run — rendered YAML (not pushed to Gitea):\n```yaml\n{rendered_yaml}\n```"
            )
            self.log_success(
                f"Dry run complete. Would push {len(scope)} device(s): "
                f"{', '.join(d['device_name'] for d in scope)}"
            )
            return rendered_yaml

        # Push policy file (always — version bump ensures the Orb agent re-runs the policy).
        try:
            self._gitea_put(
                policy_url, gitea_auth, rendered_yaml, existing_sha,
                f"Regenerate {POLICY_FILE} (v{version}) from NetBox at {timestamp}",
            )
        except requests.exceptions.RequestException as e:
            self.log_failure(f"Gitea PUT failed for {POLICY_FILE}: {e}")
            return

        self.log_success(
            f"Pushed {POLICY_FILE} (v{version}) with {len(scope)} device(s) to Gitea.\n"
            f"Devices: {', '.join(d['device_name'] for d in scope)}\n"
            f"View: {gitea_base}/admin/orb-policies/src/branch/main/{POLICY_FILE}"
        )

        # Update selector.yaml based on the activate_policy checkbox.
        try:
            self._update_selector(selector_url, gitea_auth, activate, timestamp)
        except requests.exceptions.RequestException as e:
            self.log_failure(f"Gitea operation failed for {SELECTOR_FILE}: {e}")
            return

        return rendered_yaml
