---
- name: 1 - Get Devices From Site
  uri:
      url: "{{ netbox_url }}api/dcim/devices/?name={{ inventory_hostname }}"
      method: GET
      return_content: yes
      headers:
          accept: "application/json"
          Authorization: "Token {{ netbox_token }}"
  register: device

- name: 2 - Get Site Details
  uri:
      url: "{{ netbox_url }}api/dcim/sites/?name={{ device.json.results[0]['site']['name'] }}"
      method: GET
      return_content: yes
      headers:
          accept: "application/json"
          Authorization: "Token {{ netbox_token }}"
  register: site

- name: 3 - Get List of VLANs for Site {{ device.json.results[0]['site']['name'] }}
  uri:
      url: "{{ netbox_url }}api/ipam/vlans/?site_id={{ site.json.results[0]['id'] }}"
      method: GET
      return_content: yes
      headers:
          accept: "application/json"
          Authorization: "Token {{ netbox_token }}"
  register: vlans

# Uncomment for debugging the JSON Data registered by a play
# Change the var value to whatever you need eg. var: vlans.json.results
#- name: Display Json Data
#  ansible.builtin.debug:
#    var: vlans.json.results

# Uncomment to display the Ansible Host Vars for a host
# - name: Display all variables/facts known for a host
#   ansible.builtin.debug:
#     var: hostvars[inventory_hostname]

- name: Configure VLANs on Arista Switches
  arista.eos.eos_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vid }}"
  with_items: "{{ vlans.json.results }}"
